### ISSUE TITLE
sendRequest to take a DataRequest

### ISSUE THREAD

**Issue by wassimseif** [NijiDigital/NetworkStack#18]
It's really confusing that you can build a request like this in network stack 
```
let request : DataRequest? = networkStack.request(method: .get, route: APIRouter.listUsers)
```
but there's no method to send this request with JSON response and expect `Observable<(HTTPURLResponse, Any)>`
The method for sending a request and expecting a JSON response is this one 
```
    public func sendRequestWithJSONResponse(requestParameters: RequestParameters,
                                            queue: DispatchQueue = DispatchQueue.global(qos: .default))
```
which takes `RequestParameters` and rebuilds the request. Why not a function that takes a `DataRequest` ?

**Comment by StevenWatremez** [comment]
Yep it's really confusing and we are working on `Alamofire` methods and APIs exposure. Thanks for your feedback.

If you want to know about `NetworkStack` implementation you can see the [README](https://github.com/NijiDigital/NetworkStack/blob/NetworkStack-documentation/README.md) of our work in progress PR on `NetworkStack-documentation` branch.
