### ISSUE TITLE
RxSwift dependency includes deprecated UIWebView API

### ISSUE THREAD

**Issue by QuentinArnault** [NijiDigital/NetworkStack#29]
RxSwift dependency contains references to `UIWebView` which is now deprecated. Apple starts to reject new applications with references to `UIWebView`.

RxSwift has a branch `swift5.1` without this reference to `UIWebView`.

NetworkStack should use this branch.

**Comment by QuentinArnault** [comment]
I created a fork to add the possibility to use swift5.1 branch of RxSwift but, as this version is not yet officialy released, we cannot declare this dependency directly in NetworkStack podspec.

https://github.com/QuentinArnault/NetworkStack/tree/feature/upgrade_RxSwift

**Comment by rrolland** [comment]
Hi @QuentinArnault , this issue is now fixed with the new 0.1.7 (which use rxSwift and RxCocoa 5.1)
